---
collections:
  - name: redhat.satellite
    src: https://aap-pah.ekeberg.io/api/galaxy/content/rh-certified/

  - name: redhat.system_roles
    src: https://aap-pah.ekeberg.io/api/galaxy/content/rh-certified/

